stages:
  - test
  - deploy

before_script:
  # display centos version
  - cat /etc/issue

  # Pull required packages
  - python3 -m pip install pytest pytest-cov

pytest:
  stage: test
  timeout: 20m
  script:
    - python3 -m pytest --cov=src --cov-report html --cov-report term
  coverage: '/TOTAL\s*[0-9]*\s*[0-9]*\s*(\d+%)/'

sphinx:
  stage: test
  timeout: 20m
  script:
    - cd doc/
    - python3 -m pip install -r requirements.txt
    - bash make_html_docs.sh

publish coverage:
  stage: deploy
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - python3 -m pytest --cov=src --cov-report html --cov-report term
    - rm -rf /home/josbrau/html_files/LoadEnv/coverage
    - mkdir -p /home/josbrau/html_files/LoadEnv/coverage
    - mv htmlcov/* /home/josbrau/html_files/LoadEnv/coverage/
  coverage: '/TOTAL\s*[0-9]*\s*[0-9]*\s*(\d+%)/'

publish docs:
  stage: deploy
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - cd doc/
    - python3 -m pip install -r requirements.txt
    - bash make_html_docs.sh
    - rm -rf /home/josbrau/html_files/LoadEnv/doc
    - mkdir -p /home/josbrau/html_files/LoadEnv/doc
    - mv html/* /home/josbrau/html_files/LoadEnv/doc/
