stages:
  - test
  - deploy

before_script:
  # display centos version
  - cat /etc/issue

  # Pull required packages
  # See https://pip.pypa.io/en/stable/reference/pip_install/#git : useful data on how to format this link
  #     https://stackoverflow.com/a/35998253/2059999 : also useful for some info on how to write the target
  - python3 -m pip install --user -U py pytest pytest-cov
  - python3 -m pip install --user -U git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/ConfigParserEnhanced.git@master#egg=configparserenhanced
  - python3 -m pip install --user -U git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/SetEnvironment.git@master#egg=setenvironment
  - python3 -m pip install --user -U git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/DetermineSystem.git@master#egg=determinesystem
  - python3 -m pip install --user -U git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/KeywordParser.git@master#egg=keywordparser
  - python3 -m pip install --user -U git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/LoadEnv.git@master#egg=loadenv
  - python3 -m pip install --user -U git+https://gitlab+deploy-token-CI:${CI_GROUP_READ_TOKEN}@internal.gitlab.server/trilinos-devops-consolidation/code/SetProgramOptions.git@master#egg=setprogramoptions

pytest:
  stage: test
  timeout: 20m
  script:
    - python3 -m pytest --color=yes -rs -vv --cov=gen_config --cov=src --cov-report html --cov-report term
  coverage: '/TOTAL\s*[0-9]*\s*[0-9]*\s*(\d+%)/'

sphinx:
  stage: test
  timeout: 20m
  script:
    - cd doc/
    - python3 -m pip install -U -r requirements.txt
    - bash make_html_docs.sh

publish coverage:
  stage: deploy
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - python3 -m pytest --cov=load_env --cov=src --cov-report html --cov-report term
    - rm -rf /home/josbrau/html_files/GenConfig/coverage
    - mkdir -p /home/josbrau/html_files/GenConfig/coverage
    - mv htmlcov/* /home/josbrau/html_files/GenConfig/coverage/
  coverage: '/TOTAL\s*[0-9]*\s*[0-9]*\s*(\d+%)/'

publish docs:
  stage: deploy
  timeout: 20m
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - cd doc/
    - python3 -m pip install -U -r requirements.txt
    - bash make_html_docs.sh
    - rm -rf /home/josbrau/html_files/GenConfig/doc
    - mkdir -p /home/josbrau/html_files/GenConfig/doc
    - mv html/* /home/josbrau/html_files/GenConfig/doc/
